// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANKWd4g3EeSMxYK6cbOIIadaEzHs7HgZ4',
    appId: '1:569705544426:android:2806fe9eebf70e8c45b593',
    messagingSenderId: '569705544426',
    projectId: 'petcare-81455',
    storageBucket: 'petcare-81455.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmtmS1C2ia-eRI_YCBSHGs5sMpJJWHSE',
    appId: '1:569705544426:ios:e1a1d1b55eb661ee45b593',
    messagingSenderId: '569705544426',
    projectId: 'petcare-81455',
    storageBucket: 'petcare-81455.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2LmpMFwqsM2e1cAyC9095NhwoAPKKCrA',
    appId: '1:569705544426:web:2c44422e8a144e9c45b593',
    messagingSenderId: '569705544426',
    projectId: 'petcare-81455',
    authDomain: 'petcare-81455.firebaseapp.com',
    storageBucket: 'petcare-81455.firebasestorage.app',
    measurementId: 'G-SMRYCF2CM9',
  );
}
