// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHecvuJWR0euEua8reZwNqSddXWtQzovQ',
    appId: '1:668771715108:android:409eee9c4994e2363330b1',
    messagingSenderId: '668771715108',
    projectId: 'petcare-4759b',
    storageBucket: 'petcare-4759b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD411muDQBVCL294VO01a_tYLZeYngJVGQ',
    appId: '1:668771715108:ios:310bec045be5cac53330b1',
    messagingSenderId: '668771715108',
    projectId: 'petcare-4759b',
    storageBucket: 'petcare-4759b.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR0nT77BWgPvgDTso42Ts3nOEsJIng7BY',
    appId: '1:668771715108:web:d244f448d81c7ace3330b1',
    messagingSenderId: '668771715108',
    projectId: 'petcare-4759b',
    authDomain: 'petcare-4759b.firebaseapp.com',
    storageBucket: 'petcare-4759b.firebasestorage.app',
    measurementId: 'G-ME96495RCQ',
  );
}
